# Generated by Django 3.1 on 2020-09-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descr', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('publisher', models.TextField(max_length=50)),
            ],
        ),
    ]
